spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concert?serverTimezone=Asia/Seoul
    username: jay
    password: jay
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: joswxx@gmail.com
    password: osikztmwyrpzppwm
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

