spring:
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8088
  application:
    name: main
server:
  port: 8090
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/





  #spring:
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/concert?serverTimezone=Asia/Seoul
  #    username: jay
  #    password: jay
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #
  #  jpa:
  #    hibernate:
  #      ddl-auto: none
  #    properties:
  #      hibernate:
  #        format_sql: true
  #        show_sql: true
  #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #
  #
  #  servlet:
  #    multipart:
  #      max-file-size: 50MB
  #      max-request-size: 50MB
  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username: joswxx@gmail.com
  #    password: osikztmwyrpzppwm
  #    properties:
  #      mail:
  #        smtp:
  #          starttls:
  #            enable: true
  #          auth: true
  #  security:
  #    oauth2:
  #      client:
  #        registration:
  #          google:
  #            client-id: 786598952218-4q0kg3ub1ik1qnt22cbudhdhd8a5vgld.apps.googleusercontent.com
  #            client-secret: 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
  #            scope:
  #              - email
  #              - profile
  #            redirect-uri: http://localhost:8080/oauth2/callback/google



#          kakao:
#            client-id:
#            client-secret:
#            scope:
#            redirect-uri: http://localhost:8080/oauth2/callback/kakao
#            authorization-grant-type:
#            client-name: kakao
#            client-authentication-method: POST
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#oauth:
#  jwt:
#    secret:
#      6B64DCA4E72F58EDIKU9AAB215FE7ASDACZWQEQWEQEQWE
#  oauth2:
#      authorizedRedirectUri: "http://localhost:8080/oauth2/redirect"